/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.layered.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.layered.controller.CustomerController;
import pos.layered.dto.CustomerDto;
import pos.layered.firstPage;

/**
 *
 * @author DELL
 */
public class CustomerView extends javax.swing.JFrame {
      private CustomerController customerController;
    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        customerController=new CustomerController();
        initComponents();
        loadAllCustomers();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        custIdLabel = new javax.swing.JLabel();
        custIdText = new javax.swing.JTextField();
        custTitleLabel1 = new javax.swing.JLabel();
        custDobLabel3 = new javax.swing.JLabel();
        custNameLabel4 = new javax.swing.JLabel();
        custTitleText1 = new javax.swing.JTextField();
        custNameText2 = new javax.swing.JTextField();
        custDobText3 = new javax.swing.JTextField();
        custAddressText5 = new javax.swing.JTextField();
        custSalaryText6 = new javax.swing.JTextField();
        custAddressLabel6 = new javax.swing.JLabel();
        custCityLabel7 = new javax.swing.JLabel();
        custProvinceText8 = new javax.swing.JTextField();
        custCityText9 = new javax.swing.JTextField();
        custZipLabel8 = new javax.swing.JLabel();
        custProvinceLabel9 = new javax.swing.JLabel();
        deleteButton1 = new javax.swing.JButton();
        addButton1 = new javax.swing.JButton();
        updateButton1 = new javax.swing.JButton();
        custSalaryLabel9 = new javax.swing.JLabel();
        custZipText7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custtable = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        custIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custIdLabel.setText("Customer ID");

        custTitleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custTitleLabel1.setText("Customer Title");

        custDobLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custDobLabel3.setText("Customer DOB");

        custNameLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custNameLabel4.setText("Cust Name");

        custDobText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custDobText3ActionPerformed(evt);
            }
        });

        custAddressText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custAddressText5ActionPerformed(evt);
            }
        });

        custAddressLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custAddressLabel6.setText("Address");

        custCityLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custCityLabel7.setText("City");

        custProvinceText8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custProvinceText8ActionPerformed(evt);
            }
        });

        custZipLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custZipLabel8.setText("Postal code");

        custProvinceLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custProvinceLabel9.setText("Province");

        deleteButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteButton1.setText("Delete Cusomer");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        addButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton1.setText("Save Customer");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        updateButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateButton1.setText("Update Customer");
        updateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton1ActionPerformed(evt);
            }
        });

        custSalaryLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custSalaryLabel9.setText("Customer Salary");

        custZipText7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custZipText7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(custDobLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addComponent(custTitleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(custIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(custNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custAddressLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custCityLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custProvinceLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custProvinceText8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(custDobText3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(custIdText)
                            .addComponent(custNameText2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(custTitleText1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(deleteButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(custCityText9))
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(updateButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(custZipLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)))
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(custZipText7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addButton1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(custSalaryLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(custSalaryText6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(custAddressText5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custIdLabel)
                    .addComponent(custIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custSalaryLabel9)
                    .addComponent(custSalaryText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(custDobLabel3)
                        .addComponent(custDobText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custTitleText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custTitleLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custNameLabel4))
                        .addGap(37, 37, 37)))
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custAddressText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custAddressLabel6)))
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(custCityText9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(custCityLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(custZipText7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(custZipLabel8))
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(custProvinceText8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(custProvinceLabel9)))
                .addGap(102, 102, 102)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton1)
                    .addComponent(updateButton1)
                    .addComponent(addButton1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Customer Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        custtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        custtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(custtable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        cancelButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custDobText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custDobText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custDobText3ActionPerformed

    private void custAddressText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custAddressText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custAddressText5ActionPerformed

    private void custProvinceText8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custProvinceText8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custProvinceText8ActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        deleteCustomer();
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
           addCustomer();       
    }//GEN-LAST:event_addButton1ActionPerformed

    private void updateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton1ActionPerformed
          try {
              updateCustomer();
          } catch (Exception ex) {
              Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_updateButton1ActionPerformed

    private void custZipText7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custZipText7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custZipText7ActionPerformed

    private void custtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custtableMouseClicked
          try {
              searchCustomer();
          } catch (Exception ex) {
              Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_custtableMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
        new firstPage().setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel custAddressLabel6;
    private javax.swing.JTextField custAddressText5;
    private javax.swing.JLabel custCityLabel7;
    private javax.swing.JTextField custCityText9;
    private javax.swing.JLabel custDobLabel3;
    private javax.swing.JTextField custDobText3;
    private javax.swing.JLabel custIdLabel;
    private javax.swing.JTextField custIdText;
    private javax.swing.JLabel custNameLabel4;
    private javax.swing.JTextField custNameText2;
    private javax.swing.JLabel custProvinceLabel9;
    private javax.swing.JTextField custProvinceText8;
    private javax.swing.JLabel custSalaryLabel9;
    private javax.swing.JTextField custSalaryText6;
    private javax.swing.JLabel custTitleLabel1;
    private javax.swing.JTextField custTitleText1;
    private javax.swing.JLabel custZipLabel8;
    private javax.swing.JTextField custZipText7;
    private javax.swing.JTable custtable;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateButton1;
    // End of variables declaration//GEN-END:variables

  
    private void addCustomer() {
          try {
              CustomerDto customerDto = new CustomerDto(custIdText.getText(),
                      custTitleText1.getText(),
                      custNameText2.getText(),
                      custDobText3.getText(),
                      Double.parseDouble(custSalaryText6.getText()),
                      custCityText9.getText(),
                      custAddressText5.getText(),
                      custZipText7.getText(),
                      custProvinceText8.getText());
              
              // System.out.println("Customer  : "+customer);// prnits customer details
              // System.out.println("Customer  : "+customer.toString());// prnits customer details
              String resp = customerController.addCustomer(customerDto);
              JOptionPane.showMessageDialog(this, resp);
               clear();
              loadAllCustomers();
          } catch (Exception ex) {
              Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
          }
    }
    
    public void clear(){
             custIdText.setText("");
             custTitleText1.setText("");
             custNameText2.setText("");
             custDobText3.setText("");
             custSalaryText6.setText("");
             custCityText9.setText("");
             custAddressText5.setText("");
             custZipText7.setText("");
             custProvinceText8.setText("");
    }
     private void loadAllCustomers() {

          try {
              String[] collumns = {"ID", "Name", "Salary", "Address", "Postal Code", "Province"};
              DefaultTableModel dtm = new DefaultTableModel(collumns, 0) {
                  @Override
                  public boolean isCellEditable(int row, int column) {
                      return false;
                  }
              };
              custtable.setModel(dtm);
              ArrayList<CustomerDto> customers = customerController.getAllCustomers();
              for (CustomerDto customer : customers) {
                  Object[] rowData = {customer.getId(), customer.getTitle() + " " + customer.getName(), customer.getAdress()+ "," + customer.getSalary(), customer.getCity(), customer.getZip(), customer.getProvince()};
                  dtm.addRow(rowData);
              }
          
          } catch (Exception ex) {
              Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this, ex.getMessage());
              }
    }

    private void updateCustomer() throws Exception {
     CustomerDto customer = new CustomerDto(custIdText.getText(),
                     custTitleText1.getText(),
                      custNameText2.getText(),
                      custDobText3.getText(),
                      Double.parseDouble(custSalaryText6.getText()),
                      custCityText9.getText(),
                      custAddressText5.getText(),
                      custZipText7.getText(),
                      custProvinceText8.getText());

            String resp = customerController.updateCustomer(customer);
            JOptionPane.showMessageDialog(this, resp);
            clear();
            loadAllCustomers();
    }

    private void deleteCustomer() {
          try {
              String resp = customerController.deleteCustomer(custIdText.getText());
              JOptionPane.showMessageDialog(this, resp);
              clear();
              loadAllCustomers();
          } catch (Exception ex) {
              Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
          }
    }
    

    private void searchCustomer() throws Exception {
         try {
            String custID = custtable.getValueAt(custtable.getSelectedRow(), 0).toString();
            CustomerDto customerModel = customerController.getCustomer(custID);

            if (customerModel != null) {
                custIdText.setText(customerModel.getId());
                custTitleText1.setText(customerModel.getTitle());
                custNameText2.setText(customerModel.getName());
                custDobText3.setText(customerModel.getDob());
                custSalaryText6.setText(Double.toString(customerModel.getSalary()));
                custCityText9.setText(customerModel.getCity());
                custAddressText5.setText(customerModel.getAdress());
                custZipText7.setText(customerModel.getZip());
                custProvinceText8.setText(customerModel.getProvince());
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }    

