/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.layered.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.layered.controller.ItemController;
import pos.layered.dto.CustomerDto;
import pos.layered.dto.ItemDto;
import pos.layered.firstPage;

/**
 *
 * @author DELL
 */
public class ItemView extends javax.swing.JFrame {
      private ItemController itemController;
    /**
     * Creates new form ItemView
     */
    public ItemView() {
        itemController=new ItemController();
        initComponents();
        loadAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        itemcodeLabel = new javax.swing.JLabel();
        itemCodeText = new javax.swing.JTextField();
        itemdiscriptionLabel = new javax.swing.JLabel();
        itemPriceLabel = new javax.swing.JLabel();
        itemPacksizeLabel = new javax.swing.JLabel();
        itemDiscriptionText1 = new javax.swing.JTextField();
        itemPacksizeText = new javax.swing.JTextField();
        itemPriceText = new javax.swing.JTextField();
        itemqohLabel = new javax.swing.JLabel();
        itemQOHText = new javax.swing.JTextField();
        deleteitemButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        updateitemButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        headerlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemcodeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemcodeLabel.setText("Item Code");

        itemdiscriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemdiscriptionLabel.setText("Discription");

        itemPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPriceLabel.setText("Unit Price");

        itemPacksizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPacksizeLabel.setText("Pack Size");

        itemDiscriptionText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDiscriptionText1ActionPerformed(evt);
            }
        });

        itemPacksizeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPacksizeTextActionPerformed(evt);
            }
        });

        itemPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPriceTextActionPerformed(evt);
            }
        });

        itemqohLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemqohLabel.setText("QOH");

        deleteitemButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteitemButton.setText("Delete Item");
        deleteitemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteitemButtonActionPerformed(evt);
            }
        });

        addItemButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        updateitemButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateitemButton.setText("Update Item");
        updateitemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateitemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(itemPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemdiscriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addComponent(itemcodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(itemPacksizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addComponent(itemqohLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemDiscriptionText1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPacksizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemQOHText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(deleteitemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(updateitemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(addItemButton)
                        .addGap(32, 32, 32))))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemcodeLabel)
                    .addComponent(itemCodeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemDiscriptionText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemdiscriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPacksizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPacksizeLabel))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemqohLabel)
                    .addComponent(itemQOHText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteitemButton)
                    .addComponent(updateitemButton)
                    .addComponent(addItemButton))
                .addContainerGap())
        );

        headerlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlabel.setText("Manage Item");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerlabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        cancelButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDiscriptionText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDiscriptionText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemDiscriptionText1ActionPerformed

    private void itemPacksizeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPacksizeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPacksizeTextActionPerformed

    private void itemPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPriceTextActionPerformed

    private void deleteitemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteitemButtonActionPerformed
         deleteItem();       
    }//GEN-LAST:event_deleteitemButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
         addItem();
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void updateitemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateitemButtonActionPerformed
         updateItem();       
    }//GEN-LAST:event_updateitemButtonActionPerformed

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
       getItem();
    }//GEN-LAST:event_itemTableMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
        new firstPage().setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteitemButton;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JTextField itemCodeText;
    private javax.swing.JTextField itemDiscriptionText1;
    private javax.swing.JLabel itemPacksizeLabel;
    private javax.swing.JTextField itemPacksizeText;
    private javax.swing.JLabel itemPriceLabel;
    private javax.swing.JTextField itemPriceText;
    private javax.swing.JTextField itemQOHText;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel itemcodeLabel;
    private javax.swing.JLabel itemdiscriptionLabel;
    private javax.swing.JLabel itemqohLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateitemButton;
    // End of variables declaration//GEN-END:variables

    public void clear(){
      itemCodeText.setText("");
          itemDiscriptionText1.setText("");
      itemPacksizeText.setText("");
      itemPriceText.setText("");
      itemQOHText.setText("");
    }
   
    private void addItem() {
          try {
              ItemDto itemDto=new ItemDto(itemCodeText.getText(),
                      itemDiscriptionText1.getText(),
                      itemPacksizeText.getText(),
                      Double.parseDouble(itemPriceText.getText()),
                      Integer.parseInt(itemQOHText.getText()));
              
              String resp = itemController.addItem(itemDto);
              JOptionPane.showMessageDialog(this, resp);
              clear();
              loadAllItems();
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(this, ex.getMessage());
              Logger.getLogger(ItemView.class.getName()).log(Level.SEVERE, null, ex);
          }
    }

    private void updateItem() {
          try {
              ItemDto itemDto=new ItemDto(itemCodeText.getText(),
                      itemDiscriptionText1.getText(),
                      itemPacksizeText.getText(),
                      Double.parseDouble(itemPriceText.getText()),
                      Integer.parseInt(itemQOHText.getText()));
              
              String resp=itemController.updateItem(itemDto);
              JOptionPane.showMessageDialog(this, resp);
              clear();
              loadAllItems();
          } catch (Exception ex) {
              Logger.getLogger(ItemView.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this, ex.getMessage());
          }
    }

    private void deleteItem() {
          try {
              String resp = itemController.deleteCustomer(itemCodeText.getText());
              JOptionPane.showMessageDialog(this, resp);
              clear();
              loadAllItems();
          } catch (Exception ex) {
              Logger.getLogger(ItemView.class.getName()).log(Level.SEVERE, null, ex);
          JOptionPane.showMessageDialog(this, ex.getMessage());
          }
    }
    
    
    public void loadAllItems(){
          try {
              String[] collumns = {"ItemCode", "Description", "PackSize", "UnitPrice"," QtyOnHand"};
              DefaultTableModel dtm = new DefaultTableModel(collumns, 0) {
                  @Override
                  public boolean isCellEditable(int row, int column) {
                      return false;
                  }
              };
              itemTable.setModel(dtm);
              ArrayList<ItemDto>items=itemController.getAllItem();
              for (ItemDto item : items) {
                  Object []row={item.getItemcode(),item.getDiscription(),item.getPacksize(),item.getUnitprice(),item.getQoh()};
                  dtm.addRow(row);
              }
          } catch (Exception ex) {
              Logger.getLogger(ItemView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
          }
    }

    private void getItem() {
          try {
              String orderid = itemTable.getValueAt(itemTable.getSelectedRow(), 0).toString();
              ItemDto itemDto = itemController.getItem(orderid);
              
              if (itemDto != null) {
                  itemCodeText.setText(itemDto.getItemcode());
                  itemDiscriptionText1.setText(itemDto.getDiscription());
                  itemPacksizeText.setText(itemDto.getPacksize());
                  itemPriceText.setText(Double.toString(itemDto.getUnitprice()));
                  itemQOHText.setText(Integer.toString(itemDto.getQoh()));
                  
              } else {
                  JOptionPane.showMessageDialog(this, "Customer Not Found");
              }
          } catch (Exception ex) {
              Logger.getLogger(ItemView.class.getName()).log(Level.SEVERE, null, ex);
          }
    }

}

