/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.layered;

import pos.layered.view.CustomerView;
import pos.layered.view.ItemView;
import pos.layered.view.OrderView;

/**
 *
 * @author DELL
 */
public class firstPage extends javax.swing.JFrame {

    /**
     * Creates new form firstPage
     */
    public firstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanle = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        customerButton = new javax.swing.JButton();
        itemButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(0, 204, 204));
        welcomeLabel.setText("Welcome To The HomePage");
        basePanle.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, -1));

        customerButton.setBackground(new java.awt.Color(153, 153, 153));
        customerButton.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        customerButton.setText("CUSTOMER");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        basePanle.add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        itemButton.setBackground(new java.awt.Color(153, 153, 153));
        itemButton.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        itemButton.setText("item");
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });
        basePanle.add(itemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 130, -1));

        orderButton.setBackground(new java.awt.Color(153, 153, 153));
        orderButton.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        orderButton.setText("ORDER");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        basePanle.add(orderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 130, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        basePanle.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\WNZ1rh.jpg")); // NOI18N
        basePanle.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basePanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanle, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        dispose();
        new OrderView().setVisible(true);    }//GEN-LAST:event_orderButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        dispose();
        new CustomerView().setVisible(true);    }//GEN-LAST:event_customerButtonActionPerformed

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        dispose();
        new ItemView().setVisible(true);    }//GEN-LAST:event_itemButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();    }//GEN-LAST:event_jButton1ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanle;
    private javax.swing.JButton customerButton;
    private javax.swing.JButton itemButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
